### ISSUE TITLE
Invalid IRI error

### ISSUE THREAD

**Issue by tfrancart** [logseq/rdf-export#2]
```
 Parsing 23 files...
Writing 46 triples to file ../kg-export.ttl
Run cd _rdf-export && yarn ttl ../kg-export.ttl
yarn run v1.22.19
$ /home/runner/work/digital-logbook/digital-logbook/_rdf-export/node_modules/.bin/ttl ../kg-export.ttl
ERROR: Invalid IRI on line 45.
```

What could be the reason ? 
I have page names with whitespaces in them, but I can't see any other special characters.
I have aliases too. 

Can a more detailled log be added in the action so that we can see where the problem is ?

**Comment by logseq-cldwalker** [comment]
For ttl validation, the action is using https://www.npmjs.com/package/turtle-validator. I don't think there's an option for increased verbosity. Feel free to share the failing ttl here or try running it locally and see if there's more description

**Comment by tfrancart** [comment]
I can't reproduce the error now. I will re-open and will try to see the local ttl file, now that I am able to run the script locally. Thanks for the support !
